INSERT INTO Course (courseCode,courseName,teacher,credits,semester)
VALUES
	(0,'Machine Learning for Text Mining','Lance Shelton',2,'W'),
	(1,'Search Engines','Elizabeth Prince',4,'S'),
	(2,'Neural Networks for NLP','Kevin Cline',7,'W'),
	(3,'Machine Learning for Signal Processing','Castor Roberson',8,'S'),
	(4,'Advanced Multimodal Machine Learning','Shea Taylor',7,'S'),
	(5,'Design of Intelligent Information Systems','Chanda Reyes',8,'W'),
	(6,'Machine Learning with Large Datasets','Briar Fry',7,'W'),
	(7,'Conversational Machine Learning','Driscoll Sloan',9,'S'),
	(8,'Advanced Machine Learning: Theory & Methods (was 10702)','Justine Mcgee',3,'W'),
	(9,'Foundations of Cyber Physical Systems','Ryan Wilder',2,'S'),
	(10,'Database Systems','Amy Cohen',10,'W'),
	(11,'Practical Data Science','Yeo Terry',2,'W'),
	(12,'Advanced Cloud Computing','Bruce Kramer',3,'S'),
	(13,'Graduate Artificial Intelligence','Hiram Hammond',9,'S'),
	(14,'Computer Vision','Charlotte Goodman',6,'W'),
	(15,'Medical Image Analysis','Todd Barton',9,'S'),
	(16,'Sensing and Sensors','Nissim Summers',5,'W'),
	(17,'Visual Learning and Recognition','Jordan Padilla',3,'W'),
	(18,'Web Application Development','Keefe Palmer',2,'W'),
	(19,'Management of Software Development','Debra Rowe',7,'S'),
	(20,'Methods: Deciding What to Design','Ali Puckett',3,'W'),
	(21,'Managing Software Development','Cassandra Ware',4,'S'),
	(22,'Software Engineering for Startups','William Cervantes',8,'S'),
	(23,'Fundamentals of Bioinformatics','Asher Hartman',3,'S'),
	(24,'Computational Medicine','Suki Saunders',6,'W'),
	(25,'Machine Learning','Lydia Davidson',8,'W'),
	(26,'Natural Language Processing','Dominic Burt',6,'W'),
	(27,'Deep Learning','Lucius Wilkins',7,'S'),
	(28,'Computer Vision','Karina Edwards',7,'W'),
	(29,'Fairness, Accountability, Confidentiality and Transparency in AI','Hayes Albert',4,'S'),
	(30,'Information Retrieval','Odysseus Kidd',3,'S'),
	(31,'Knowledge Representation and Reasoning','Timon Evans',3,'W'),
	(32,'European Court of Human Rights and Family Law','Wylie Lancaster',9,'S'),
	(33,'International Commercial Arbitration','Yuri Myers',3,'W'),
	(34,'International Commercial Arbitration','Aurora Humphrey',4,'W'),
	(35,'Privacy and Personal Data','Wesley Mccray',2,'W'),
	(36,'Written Communication in Legal German','Denton Mejia',6,'W'),
	(37,'Law of Domain Names and Online Marketing','Harding Wilkerson',3,'S'),
	(38,'Law of Domain Names and Online Marketing','Ginger Murphy',6,'W'),
	(39,'Human Rights Mechanism in South Asia','Perry Carter',9,'S'),
	(40,'Tax System and Constitutional Taxation','Rhoda Waters',6,'W'),
	(41,'International and EU Energy Law','Ferdinand Boyer',8,'W'),
	(42,'Free Movement of Persons in the EU','Kenyon Larsen',2,'W'),
	(43,'Human Rights in Europe','Ivory Alford',4,'W'),
	(44,'Law of International Organisations','Dillon Horn',4,'W'),
	(45,'Turkish Arbitration System','Callum Wagner',3,'S'),
	(46,'Maritime Carriers Liability under Turkish Law and International Treaties','Deborah Holt',8,'W'),
	(47,'"American Legal Racism: From the 1787 Constitution to the 2020 G. Floyd ','Dara Terry',2,'S'),
	(48,'Murder & Recent Developments"','Fuller Coleman',6,'W'),
	(49,'"The Court of Justice of the European Union and its Interaction with ','Mollie Holloway',9,'W'),
	(50,'National Legal Systems"','Quynn Beach',4,'W'),
	(51,'The European Court of Human Rights and the School','Marcia Beck',9,'S'),
	(52,'Introduction to Polish Labour Law','Wayne Sheppard',6,'W'),
	(53,'Introduction to Polish Medical Law','Ishmael Crosby',10,'S'),
	(54,'Credibility of Expert Evidence. DNA Evidence  Future Challenges','Bradley Whitfield',2,'W'),
	(55,'Artifical Intelligence, Law, and Governance','Mohammad Carney',2,'W'),
	(56,'International Law: Case of Kosovo','Caesar Hughes',9,'W'),
	(57,'"Continuing Course of Austrian Substantive Civil Law  from the Perspective ','Clio Buckley',8,'W'),
	(58,'of an Attorney"','Risa Best',10,'S'),
	(59,'Introduction into Investment Law and Arbitration','Hilda Pickett',8,'W'),
	(60,'Regulating Disruptive Technologies','Lane Sanford',2,'S'),
	(61,'Software Law','Christine Mcclure',2,'W'),
	(62,'Cybersecurity Law','Madeline Kirkland',7,'S'),
	(63,'Cybersecurity Law','Audra White',4,'S'),
	(64,'International Arbitration in the Energy Sector','Aimee George',3,'S'),
	(65,'International Arbitration in the Energy Sector','Leroy Watson',4,'S'),
	(66,'International and European Intellectual Property Law','Martena Carrillo',4,'W'),
	(67,'International and European Intellectual Property Law','Graham Maxwell',5,'W'),
	(68,'Private International Law, Intellectual Property Rights and the Internet','Ina Simmons',8,'S'),
	(69,'Private International Law, Intellectual Property Rights and the Internet','Cailin Roach',5,'S'),
	(70,'Internet Gaming and Entertainment Law','Kerry Pena',5,'S'),
	(71,'Internet Gaming and Entertainment Law','Hyatt Trujillo',8,'S'),
	(72,'German and Austrian Systems of Procedural Law','Naida Alston',2,'S'),
	(73,'German and Swiss Systems of Procedural Law','Mariam Maddox',3,'W'),
	(74,'German and Swiss Systems of Procedural Law','Raymond Mcdonald',10,'S'),
	(75,'School of Polish Law','Channing Hutchinson',8,'W'),
	(76,'School of Polish Law','Hillary Cummings',8,'S'),
	(77,'International Master Research Seminar in Comparative Law','Juliet Rich',2,'W'),
	(78,'The Twilight of Constitutionalism','Leo Stephenson',5,'W'),
	(79,'The Twilight of Constitutionalism','Emerald Vaughn',7,'S'),
	(80,'Comparative Constitutional Law and Politics','Cairo Mack',9,'S'),
	(81,'International and Czech Environmental Law','Rhoda Moss',9,'S'),
	(82,'Public Administration in the Czech Republic','Leroy Alston',9,'W'),
	(83,'Public Administration in the Czech Republic','Axel Finch',2,'S'),
	(84,'Selected problems of Czech Criminal Law','Celeste Burks',9,'W'),
	(85,'Selected problems of Czech Criminal Law','Charde Page',6,'W'),
	(86,'Selected problems of Czech Criminal Law','Dominic Wilkinson',9,'W'),
	(87,'Competition Policy and Competition Law','Daria Hayden',8,'W'),
	(88,'Competition Policy and Competition Law','Hamish Rice',6,'S'),
	(89,'Competition Policy and Competition Law','Demetrius Arnold',3,'S'),
	(90,'Czech Legal Culture','Wyoming Clark',3,'S'),
	(91,'Czech Legal Culture','Aurora Mccall',5,'S'),
	(92,'Czech Legal Culture','Gage Walsh',9,'S'),
	(93,'General Theory of Law','Scott Osborne',5,'S'),
	(94,'General Theory of Law','Chloe Vance',5,'W'),
	(95,'Introduction to Czech Private Law in European Context','Keelie Park',10,'S'),
	(96,'Introduction to Czech Private Law in European Context','Lucas Ortega',3,'W'),
	(97,'Copyright Law','Alice Aguirre',5,'W'),
	(98,'Copyright Law','Hasad Perkins',10,'W'),
	(99,'EU Law','Roanna Duke',8,'W'),
	(100,'EU Law','Lee Allison',5,'S'),
	(101,'Czech and Comparative Tax Law','Garrett Espinoza',4,'S'),
	(102,'Czech and Comparative Tax Law','Whitney Lynn',5,'W'),
	(103,'Czech and Comparative Tax Law','Yen English',4,'S'),
	(104,'European Cyberlaw','Lillith Bauer',5,'W'),
	(105,'European Cyberlaw','Amanda Conley',2,'W'),
	(106,'European Cyberlaw','Jocelyn Bright',5,'S'),
	(107,'European Private International Law','Mannix Diaz',7,'S'),
	(108,'Introduction to the European Union Law','Amir Poole',2,'S'),
	(109,'Marketing for Lawyers','Carlos Justice',8,'S'),
	(110,'Marketing for Lawyers','Yoshi Stokes',4,'W'),
	(111,'Marketing for Lawyers','Ivan Burke',4,'S'),
	(112,'European Labour Law','Adara Wells',7,'W'),
	(113,'European Labour Law','Briar Cooper',2,'S'),
	(114,'European Labour Law','Prescott Wagner',3,'W'),
	(115,'Introduction to Legal English for Erasmus Students','Yoshio Knight',4,'W'),
	(116,'Introduction to Legal English for Erasmus Students','Molly Manning',10,'W'),
	(117,'Introduction to Legal English for Erasmus Students','Oren Yates',10,'W'),
	(118,'Constitutional Adjudication  Morphology, Genealogy and Legitimacy','Bradley Russell',10,'S'),
	(119,'Constitutional Adjudication  Morphology, Genealogy and Legitimacy','Beck Roman',7,'W'),
	(120,'Work on Diploma Theses','Trevor Powers',8,'S'),
	(121,'Work on Diploma Theses','April Goff',7,'S'),
	(122,'Work on Diploma Theses','Moana Roy',4,'S'),
	(123,'Basics of EU Environmental Law','Troy Hendricks',2,'S'),
	(124,'Basics of EU Environmental Law','Keelie Oneal',2,'S'),
	(125,'Basics of EU Environmental Law','Chiquita Christian',5,'W'),
	(126,'European Economic Area','Chiquita Spears',8,'W'),
	(127,'European Economic Area','Ori Kim',5,'S'),
	(128,'Roman Law','Kevin Booth',10,'W'),
	(129,'Law of Succession in the Middle European Area','Alexandra Rios',2,'W'),
	(130,'Law of Succession in the Middle European Area','Solomon Workman',10,'W'),
	(131,'Legal Philosophy','Donovan Cunningham',5,'W'),
	(132,'Legal Philosophy','Curran Turner',4,'S'),
	(133,'Legal Philosophy','Liberty Burgess',6,'W'),
	(134,'Climate Law','Honorato Schwartz',6,'W'),
	(135,'Climate Law','Zenia Ryan',8,'W'),
	(136,'Constitutional Law of the European Union','Meredith Hinton',7,'W'),
	(137,'Constitutional Law of the European Union','Gretchen Mason',4,'W'),
	(138,'Classical Russian Literature 1','Brock Vazquez',8,'W'),
	(139,'Synatax 1','Michelle Burgess',2,'S'),
	(140,'Russian Syntax 1  Seminar','Maxine Harding',9,'S'),
	(141,'Russian Culture 1   Seminar','Madison Vincent',3,'W'),
	(142,'Practice Language Course 5','Candice Finley',6,'W'),
	(143,'Practical Russian   Seminar 5','Marsden Lester',4,'W'),
	(144,'Russian Culture and Civilization 1','Ignacia Shepard',5,'S'),
	(145,'Russian film 1','Griffin Bridges',6,'W'),
	(146,'Commercial correspondence in Russian 1','Elmo Ballard',3,'W'),
	(147,'Basics of Russian Didactics 1','Brynne West',8,'W'),
	(148,'Didactics of Russian Literary Texts 1','Gavin Russo',2,'S'),
	(149,'E resources in Russian Language Teaching','Olympia Moses',3,'W'),
	(150,'Didactics of Russian Language 1','Veda Abbott',9,'W'),
	(151,'Didactics of Russian Language 3','Phillip Suarez',2,'S'),
	(152,'Childrens Literature 1','Naida Roy',10,'S'),
	(153,'Practical Language Course 1','Ross Alston',8,'W'),
	(154,'Practical Language Course 3','Alice Hale',4,'S'),
	(155,'Historical Grammar of Russian 1','Juliet Cherry',8,'S'),
	(156,'Historical Development of Russian: Seminar 1','Nathaniel Stein',4,'S'),
	(157,'Bildung und Förderung von Menschen mit Behinderung 1','Herman Bender',10,'S'),
	(158,'Bildung und Förderung von Menschen mit Behinderung 1','Alan Booker',7,'W'),
	(159,'Introduction to Special Needs Education   Online','Heather Cochran',2,'W'),
	(160,'Special Education in International Perspectives','Risa Myers',4,'S'),
	(161,'Special Education in International Perspectives','Phelan O''Neill',7,'W'),
	(162,'Special and Inclusive Education','Nero Pugh',10,'S'),
	(163,'Special and Inclusive Education','Ralph Camacho',2,'S'),
	(164,'The Art of Advanced Public Speaking','Brandon Ellison',10,'S'),
	(165,'Seminar in microeconomics','Bertha Jensen',2,'W'),
	(166,'Diploma seminar 1','Roth Franks',2,'S'),
	(167,'Microeconomics 2','Joelle Ayala',7,'W'),
	(168,'Behavioral economics','Gay Luna',6,'W'),
	(169,'Law & Economics','Eliana Hester',6,'W'),
	(170,'Transport Investment Appraisal','Indigo Horton',6,'W'),
	(171,'Transport Economics','Beatrice Doyle',5,'W'),
	(172,'International Accounting','Michael Rodgers',5,'S'),
	(173,'Auditing','Martha Wiggins',10,'W'),
	(174,'Diploma seminar 1','Blake Strong',2,'W'),
	(175,'Financial investments','Chandler Phillips',6,'W'),
	(176,'International Finance and Institutions','Charissa Calhoun',7,'W'),
	(177,'Security Analysis and Derivatives','Ginger Wong',9,'W'),
	(178,'Structured Products','Ingrid Jacobs',4,'W'),
	(179,'Business Logistics and Transportation','Tate Mcfadden',8,'S'),
	(180,'Diploma seminar 1','Geoffrey Cantu',3,'S'),
	(181,'International Trade','Phelan Vaughan',6,'S'),
	(182,'Management 2','Nicole Daugherty',5,'W'),
	(183,'Managerial Accounting','Harriet Gutierrez',6,'S'),
	(184,'Marketing in the EU','Chase Bishop',10,'S'),
	(185,'Operations Research and ERP','Rylee Franco',3,'S'),
	(186,'Business Process Management','Samuel Burch',2,'S'),
	(187,'Corporate Social Responsibility','Wang Valenzuela',4,'S'),
	(188,'International Marketing','Brianna Cooper',7,'W'),
	(189,'Organizational Behavior','Lucy Shaw',9,'S'),
	(190,'Language II/1   English','Aristotle Emerson',6,'S'),
	(191,'Language II/1   French','Shelley Hart',2,'S'),
	(192,'Language II/1   German','Brian Jacobs',10,'W'),
	(193,'Language II/1   Russian','Faith Mckenzie',8,'W'),
	(194,'Language II/1   Spanish','Malik Skinner',3,'W'),
	(195,'Language II/2   English','Barrett Sawyer',10,'W'),
	(196,'Language II/2   French','Judith Griffin',3,'W'),
	(197,'Language II/2   German','Thomas George',2,'S'),
	(198,'Language II/2   Russian','Haley Moore',3,'S'),
	(199,'Language II/2   Spanish','Kevin Watkins',3,'S'),
	(200,'Präsentationstechniken und  fertigkeiten in Deutsch','Maggy Mckee',4,'W'),
	(201,'Diploma seminar 1','Walker Bradshaw',5,'S'),
	(202,'Public Finance 2','Shannon Romero',5,'S'),
	(203,'Applied Research in Public Policy Making','Melyssa Kelley',9,'S'),
	(204,'Civil Society, Economy and the State','Axel Herman',7,'W'),
	(205,'Labour market and socioeconomic inequalities','Sigourney Bullock',7,'W'),
	(206,'Selected Topics in Sport Science','Cairo Mayo',6,'S'),
	(207,'Ergonomics and Its Anatomical Basis','Naomi Wyatt',9,'W'),
	(208,'Corrective Exercises','Dieter Sims',6,'W'),
	(209,'Adapted Physical Activity','Lucius Leonard',3,'S'),
	(210,'Combative Activities','Pearl Ward',4,'W'),
	(211,'2D and 3D Motion Analysis','Wing Hines',6,'S'),
	(212,'Sociology in Sport','James Palmer',10,'S'),
	(213,'First Aid','Isadora Cooper',10,'W'),
	(214,'Harmonization Exercises','Adrian Carter',6,'W'),
	(215,'Hiking','Cameran Bullock',4,'S'),
	(216,'Outdoor Activities','Steel Mann',3,'W'),
	(217,'Futsal','Cara Chapman',10,'W'),
	(218,'Fitness','Jelani Glenn',3,'W'),
	(219,'Body and Mind','Hilel Richardson',5,'W'),
	(220,'Strength Training and Conditioning','Chester Duffy',10,'W'),
	(221,'Basketball','Harlan Stone',8,'W'),
	(222,'Sport Management','Nyssa Duke',9,'S'),
	(223,'Nontraditional Games','James Hull',9,'W'),
	(224,'Physiology of Sport and Exercise','Ashton Mills',10,'S'),
	(225,'Excercise & Sport Psychology','Joshua Weeks',2,'S'),
	(226,'Gymnastics','Kyle Shannon',5,'W'),
	(227,'Basic Techniques of Sports Massage','Mark Greer',6,'W'),
	(228,'Sports Volunteering','Mari Boone',5,'S'),
	(229,'Applied Sports Nutrition','TaShya Clayton',6,'S'),
	(230,'Thesis Writing and Research Seminar','Darius Mcclain',8,'W'),
	(231,'Physical Activity in Older Adult','Josiah Jacobson',5,'W');
